---

- name: Apply Supervisor configurations
  notify: reload supervisor
  template:
    src: supervisor/{{ item }}.conf.j2
    dest: /etc/supervisor/conf.d/{{ item }}.conf
  with_items:
    - rq-dashboard
    - osp-workers

- name: Apply nginx configurations
  notify: reload nginx
  template:
    src: nginx/{{ item }}.j2
    dest: /etc/nginx/sites-enabled/{{ item }}
  with_items:
    - rq-dashboard
