---

- name: Update the OSP source code
  git:
    repo: "{{ osp_repo }}"
    version: "{{ osp_branch }}"
    dest: "{{ osp_src }}"

- name: Check if a virtualenv exists
  register: env
  stat:
    path: "{{ osp_src }}/env"

# pyvenv is broken on Ubuntu 14.04.
- name: Create a Python 3 virtualenv, if necessary
  when: env.stat.isdir is not defined
  command: virtualenv --python=/usr/bin/python3.4 env
  args:
    chdir: "{{ osp_src }}"

- name: Install pip dependencies
  command: env/bin/pip3 install -r requirements.txt
  args:
    chdir: "{{ osp_src }}"

- name: Install the CLI suite
  command: env/bin/python3 setup.py develop
  args:
    chdir: "{{ osp_src }}"

- name: Configure .profile
  lineinfile:
    dest: /home/{{ ansible_ssh_user }}/.profile
    line: '{{ item }}'
  with_items: osp_profile

- name: Create the OSP config directory
  file:
    path: /etc/osp
    state: directory

- name: Apply the OSP config
  template:
    src: osp.yml.j2
    dest: /etc/osp/osp.yml
