---

- name: Install dependencies
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - python-virtualenv
    - python3-setuptools
    - python3-dev
    - libpq-dev
    - libxslt1-dev
    - libxml2-dev
    - libreoffice
