---

- name: Configure OSP workers
  become: yes

  hosts:
    - tag_osp_server
    - tag_osp_worker

  pre_tasks:
    - include_vars: local.yml
      ignore_errors: yes

  roles:
    - common
    - postgres
    - elasticsearch
    - redis
    - supervisor
    - nginx
