---

- name: Configure OSP workers
  become: yes

  hosts:
    - tag_osp_server
    - tag_osp_worker

  roles:
    - common
    - postgres
    - elasticsearch
    - redis
    - supervisor
    - nginx
