---

- name: Configure an OSP worker instance
  sudo: yes
  hosts: workers

  vars_files:
    - vars/postgres.yml

  roles:
    - common
    - postgres
    - elasticsearch
    - redis
    - supervisor
