---

- name: Provision a worker instance
  hosts: 127.0.0.1

  vars:
    worker_image: ami-9eaa1cf6
    worker_instance_type: t2.micro
    worker_subnet_id: '{{ lookup("env", "OSP_SUBNET_ID") }}'
    worker_region: us-east-1
    worker_count: 1

  tasks:

    - name: Spin up an instance
      ec2:

        image: '{{ worker_image }}'
        instance_type: '{{ worker_instance_type }}'
        vpc_subnet_id: '{{ worker_subnet_id }}'
        region: '{{ worker_region }}'
        group: osp-worker
        assign_public_ip: yes

        count_tag: osp-worker
        exact_count: '{{ worker_count }}'
        instance_tags:
          type: osp-worker
        count_tag:
          type: osp-worker
