---

max_fuzz: 3.02

blacklisted_titles:

  - letter
  - correspondence
  - poem
  - poetry
  - introduction
  - publication
  - report
  - review
  - lecture
  - speech
  - writing
  - sonnet
  - note
  - work
  - foreword
  - essay
  - book review
  - proceeding
  - play
  - journal
  - novel
  - study
  - title
  - story
  - selection
  - preface
  - handout

  - concerto
  - symphony
  - sonata
  - cantata
  - solo

blacklisted_surnames:
  - may
  - lippincott
  - page
