---

max_fuzz: 0.2344229

blacklisted_titles:
  - letter
  - correspondence
  - poem
  - introduction
  - report
  - review
  - lecture
  - speech
  - writing
  - sonnet
  - note
  - work
  - foreword
  - essay

blacklisted_surnames:
  - may
