---

max_fuzz: 0.2344229

blacklisted_titles:
  - letter
  - correspondence
  - poem
  - introduction
  - report
  - report
  - review
  - lecture
  - speech
  - writing
  - sonnet

blacklisted_surnames:
  - may
