---

max_fuzz: 3.02

blacklisted_titles:
  - letter
  - correspondence
  - poem
  - introduction
  - report
  - review
  - lecture
  - speech
  - writing
  - sonnet
  - note
  - work
  - foreword
  - essay
  - book review
  - proceeding
  - play

blacklisted_surnames:
  - may
