---

# VPC subnet to house the instances.
ec2_subnet_id: subnet-XXX

# AWS keypair to use when creating instances.
ec2_keypair: XXX

# ID of the OSP EBS snapshot.
ec2_osp_snapshot: snap-XXX

# IP address of the central data server.
osp_data_host: XXX

# Other local overrides:
# ...
